### PR TITLE
Re-add version

### PR DESCRIPTION
**Pull request by dwilkie**

### CODE REVIEW

**Comment by accursoft** [comment]
Sorry I haven't responded yet, I'm in hospital right now. The short answer is that the version field is deprecated by bower, so no.

**Comment by dwilkie** [comment]
Thanks for the reply! Hope you're ok?! There's a lot of people who use your
library with Rails and it works nicely with https://rails-assets.org but
they need a version number in bower. But I searched online and couldn't
find where the version is deprecated. In fact https://rails-assets.org
won't work without it and say that your bower.json is invalid without it.
Who is correct here?

**Comment by accursoft** [comment]
https://github.com/bower/spec/blob/master/json.md

**Comment by dwilkie** [comment]
FYI

https://github.com/rails-assets/rails-assets/issues/285

**Comment by accursoft** [comment]
I'm not familiar with rails-assets, perhaps it will take a branch name (master) or SHA.

**Comment by dwilkie** [comment]
Ok so the way I understand it is that `version` is deprecated in favor of git tags. I think you can create a tag with `git tag v1.3.3` https://git-scm.com/book/en/v2/Git-Basics-Tagging. Basically rails-assets allows you to require Caret in rails library as `rails-assets-caret` and the js will be available in your rails project. Actually Caret is a dependency of https://github.com/stripe/jquery.mobilePhoneNumber. So if this is fixed, when people install that library Caret will automatically be installed.

**Comment by accursoft** [comment]
Not simple to do this from a hospital bed without a computer. Have you tried branch name and SHA?

**Comment by dwilkie** [comment]
Man I'm so sorry I forgot! I'll see how I go with that. Hope you get well soon :pray:

**Pull request closed without merging**
